# Generated by Django 5.0.3 on 2024-06-11 22:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id_mascota', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_masco', models.CharField(choices=[('Perro', 'Perro'), ('Gato', 'Gato'), ('Ave', 'Ave'), ('Reptil', 'Reptil'), ('Roedores', 'Roedores'), ('Conejo', 'Conejo')], max_length=45)),
                ('raza_masco', models.CharField(max_length=45)),
                ('nomb_masco', models.CharField(max_length=45)),
                ('naci_masco', models.DateField()),
                ('foto_masco', models.ImageField(upload_to='mascotas/')),
            ],
            options={
                'db_table': 'mascota',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MascotaServicio',
            fields=[
                ('id_mascota_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('fech_servi_masco', models.DateField()),
            ],
            options={
                'db_table': 'mascota_servicio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nomb_produ', models.CharField(max_length=45)),
                ('desc_produ', models.CharField(max_length=60)),
                ('prec_produ', models.FloatField()),
                ('foto_produ', models.ImageField(upload_to='productos/')),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductoUsuario',
            fields=[
                ('id_producto_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('cant_producto', models.IntegerField(blank=True, null=True)),
                ('total_producto', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'producto_usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('nomb_serv', models.CharField(max_length=45)),
                ('desc_serv', models.CharField(max_length=1000)),
                ('prec_serv', models.FloatField()),
                ('imag_serv', models.ImageField(upload_to='servicios/')),
            ],
            options={
                'db_table': 'servicio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_persona', models.IntegerField(primary_key=True, serialize=False)),
                ('usua_usuar', models.CharField(blank=True, max_length=45, null=True, unique=True)),
                ('cont_usuar', models.CharField(blank=True, max_length=45, null=True)),
                ('nomb_usuar', models.CharField(blank=True, max_length=45, null=True)),
                ('apel_usuar', models.CharField(blank=True, max_length=45, null=True)),
                ('dire_usuar', models.CharField(blank=True, max_length=45, null=True)),
                ('tele_usuar', models.CharField(blank=True, max_length=45, null=True)),
                ('corr_usuar', models.CharField(blank=True, max_length=45, null=True)),
                ('tipo_usuar', models.IntegerField(blank=True, choices=[(0, 'Administrador'), (1, 'Cliente')], null=True)),
                ('foto_usuar', models.ImageField(upload_to='usuarios/')),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomb_categ', models.CharField(max_length=100, verbose_name='Nombre')),
                ('crea_categ', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titu_post', models.CharField(max_length=200, verbose_name='Título')),
                ('cont_post', models.TextField(verbose_name='Contenido')),
                ('fech_post', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de publicación')),
                ('foto_post', models.ImageField(blank=True, null=True, upload_to='BlogImg', verbose_name='Imagen')),
                ('Fcreacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('Fedicion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de edición')),
                ('categorias', models.ManyToManyField(to='Bd_mascotas.categoria', verbose_name='Categorias')),
                ('id_persona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Bd_mascotas.usuario')),
            ],
            options={
                'verbose_name': 'post',
            },
        ),
    ]
